name: Provision Infrastructure

on:
  push:
    branches:
      - ci/cd

jobs:
  configure-and-provision:
    name: Configure AWS CLI and provision infrastructure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Terraform CLI
        uses: hashicorp/setup-terraform@v3

      - name: Init Backend Resources
        run: |
          cd init/
          terraform init

      - name: Validate Backend Resources
        run: |
          cd init/
          terraform validate

      - name: Plan Backend Resources
        run: |
          cd init/
          terraform plan
        continue-on-error: true

      - name: Apply Backend Resources
        run: |
          cd init/
          terraform apply -auto-approve

      - name: Init Resources
        run: terraform init

      - name: Validate Resources
        run: terraform validate

      - name: Plan Resources
        run: terraform plan
        continue-on-error: true

      - name: Apply Resources
        run: terraform apply -auto-approve
